### ISSUE TITLE
Getting TypeError: nlp.plugin is not a function

### ISSUE THREAD

**Issue by mcnaveen** [nlp-compromise/nlp-pronounce#1]
```
nlp.plugin(nlpPronounce);
    ^

TypeError: nlp.plugin is not a function
```

**Comment by spencermountain** [comment]
thanks @the-mcnaveen looks like i forgot to update this plugin to v12
will take a look when I get a sec
cheers

**Comment by mcnaveen** [comment]
Thanks. I have one doubt.

Can we generate the pronunciation of a given word?

**Comment by spencermountain** [comment]
hey, it's published over here now 
https://github.com/spencermountain/compromise/tree/dev/plugins/pronounce
yeah, you can do `doc.terms().pronounce()`
cheers

**Comment by mcnaveen** [comment]
Still showing the same error

![image](https://user-images.githubusercontent.com/8493007/93982027-56bb5880-fd9e-11ea-96f3-dbb2dff8e89c.png)

**Comment by spencermountain** [comment]
sorry, I believe the method is now `nlp.extend()`
it's been a few years since I created this, thanks for your patience.

**Comment by mcnaveen** [comment]
Sorry for reopening the issue.

```
ninja@softinttech:~/Scripts/pronounce$ cat index.js 
var nlp = require('compromise')
var nlpPronounce = require('nlp-pronounce')
nlp.extend(nlpPronounce)

var texxt = "Phil Collins"
var pronounce = nlp.text(texxt)
t.pronounce()
// [{pronounce:"fil kolins", text:"phil collins"}]

--------------------------------------------------
ninja@softinttech:~/Scripts/pronounce$ node index.js 
/home/ninja/Scripts/pronounce/node_modules/compromise/builds/compromise.js:13879
      fn(Doc_1, world, this, Phrase_1, Term_1, Pool_1);
      ^

TypeError: fn is not a function
    at Function.nlp.extend (/home/ninja/Scripts/pronounce/node_modules/compromise/builds/compromise.js:13879:7)
    at Object.<anonymous> (/home/ninja/Scripts/pronounce/index.js:3:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```

**Comment by spencermountain** [comment]
hey @the-mcnaveen no problem
there are a couple things to change - notably, that the plugin is called `compromise-pronounce`
once you update that dependency, this should work:
```js
var nlp = require('compromise')
var nlpPronounce = require('compromise-pronounce')
nlp.extend(nlpPronounce)
var texxt = 'Phil Collins'
var doc = nlp(texxt)
console.log(doc.pronounce())

```

**Comment by mcnaveen** [comment]
Thank you so much @spencermountain

**Comment by mcnaveen** [comment]
How can I get just **pronounce** without text, normal, and terms? Is it possible?

![Selection_278](https://user-images.githubusercontent.com/8493007/94298109-2da7ed00-ff83-11ea-93f8-6d4ab58544f5.png)

**Comment by spencermountain** [comment]
you can use the javascript [.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) method
if you want the pronounciations from each term, you can do
```js
doc.terms().pronounce().map(o=> o.pronounce)
```
cheers

**Comment by mcnaveen** [comment]
It works. Thanks
